# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='admin', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default='Zhang', max_length=40),
            preserve_default=False,
        ),
    ]
