# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('user', '0003_auto_20170426_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='lessons',
            field=models.ManyToManyField(to='education.Lesson'),
        ),
    ]
